---
title: "Untitled"
author: "Aravindan"
date: "17/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library("astsa")
library("forecast")
library("dplyr")
library("xts")
library("lubridate")
setwd("E:/Nalanda/TIme-Series-R")
data=read.csv("Rajasthan.csv")
windspeed=ts(data$Wind.Speed)
year=data$Year
month=data$Month
day=data$Day
time=as.Date(ymd(paste(data$Year,monthly_data$Month,"15",sep="-")))
monthly_data=data %>% group_by(Year,Month) %>% summarize(windspeed=mean(Wind.Speed,na.rm=T))
daily_data=data %>% group_by(Year,Month,Day) %>% summarize(windspeed=mean(Wind.Speed,na.rm=T))
```


```{r}
tsdisplay(monthly_data$windspeed)
ws=monthly_data$windspeed
par(mfrow=c(1,1))
acf(diff(diff(ws,12)),100)
pacf(diff(diff(ws,12)),100)
```


```{r}
#AR coefficients 1,2,3
#MA coefficients 1,2
aic101=sarima(ws,1,0,1,0,1,1,12)$AIC
aic102=sarima(ws,1,0,2,0,1,1,12)$AIC
aic201=sarima(ws,2,0,1,0,1,1,12)$AIC
aic202=sarima(ws,2,0,2,0,1,1,12)$AIC
aic301=sarima(ws,3,0,1,0,1,1,12)$AIC
aic302=sarima(ws,3,0,2,0,1,1,12)$AIC

aic111=sarima(ws,1,1,1,0,1,1,12)$AIC
aic112=sarima(ws,1,1,2,0,1,1,12)$AIC
aic211=sarima(ws,2,1,1,0,1,1,12)$AIC
aic212=sarima(ws,2,1,2,0,1,1,12)$AIC
aic311=sarima(ws,3,1,1,0,1,1,12)$AIC
aic312=sarima(ws,3,1,2,0,1,1,12)$AIC
```
```{r}

```

```{r}
model=arima(x=monthly_data$windspeed[1:150],order=c(3,0,1),seasonal=list(order=c(0,1,1),period=12)) #for monthly data 
ind <- seq(as.Date("2000-01-01"), as.Date("2014-12-31"), by = "month")
plot(forecast(model,30))
plot(monthly_data$windspeed,type="l",col="red")
fc=forecast(model,30)
ind <- seq(as.Date("2012-07-01"), as.Date("2014-12-31"), by = "month")
plot(x=ind,y=fc$mean,type="l",col="blue")
lines(x=ind,y=monthly_data$windspeed[151:180],col="red")
legend("topleft",c("predicted","Actual"),fill=c("blue","red"))

```
```{r}

#ylim=c(min(fc$mean,monthly_data$windspeed[151:180]),max(fc$mean,monthly_data$windspeed[151:180]))
```
```{r}
autoplot(fc)
```

